apiVersion: v1
kind: ConfigMap
metadata:
  name: jobapp-config
  labels:
    app: jobapp
data:
  allowed-hosts: "localhost,127.0.0.1,jobapp,jobapp.default,jobapp.default.svc.cluster.local"
  log-level: "INFO"
