apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobapp-ingress
  labels:
    app: jobapp
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jobapp-service
            port:
              number: 80
