apiVersion: v1
kind: ServiceAccount
metadata:
  name: django-app-sa
  namespace: default
  labels:
    app: django-job-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: django-app-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: django-app-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: django-app-role
subjects:
  - kind: ServiceAccount
    name: django-app-sa
    namespace: default
