apiVersion: v1
kind: Service
metadata:
  name: jobapp-service
  namespace: default
  labels:
    app: jobapp
    name: jobapp-service
spec:
  type: ClusterIP
  selector:
    app: jobapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: jobapp-nodeport
  namespace: default
  labels:
    app: jobapp
    name: jobapp-nodeport
    tier: nodeport
spec:
  type: NodePort
  selector:
    app: jobapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
