pipeline {
        agent {
            docker { image 'python:3.9' }
        }
        stages {
            stage('Build') {
                steps {
                    sh 'pip install -r requirements.txt'
                }
            }

            stage('Test') {
                steps {
                    sh 'python app/manage.py test'
                }
            }

            stage('Deploy') {
                steps {
                    sh 'echo not yet...'
                }
            }
        }
    }















// pipeline {
//     agent any 
//     stages {
//         stage('Build') { 
//             steps {
//                 sh "echo Building" 
//             }
//         }
//         stage('Test') { 
//             steps {
//                 sh "echo testing" 
//             }
//         }
//         stage('Deploy') { 
//             steps {
//                 sh "echo Deploying" 
//             }
//         }
//     }
// }