pipeline {
    agent any

    environment {
        // Define the Docker image name and tag for Docker Hub
        DOCKER_IMAGE = "sachinkumar26/djproject:1.0"
        DOCKER_REGISTRY = "docker.io" // Docker Hub registry URL
        
        // Hardcoded Docker credentials (NOT recommended for production)
        DOCKER_USERNAME = "sachinkumar26"
        DOCKER_PASSWORD = "Aarush@123#"
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your GitHub repository
                git url: 'https://github.com/sachinvishwakarma26/SachinJobApp1.git', branch: 'master'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image using the Dockerfile from the specified path
                    sh 'docker build -t $DOCKER_IMAGE -f djproject/Dockerfile .'
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                script {
                    // Optionally run tests if your Dockerfile has test scripts defined
                    sh 'docker run $DOCKER_IMAGE pytest'
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    // Log in to Docker Hub using the hardcoded credentials
                    sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY'
                    
                    // Push the image to Docker Hub
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Run the container locally (optional)
                    sh 'docker run -d -p 8000:8000 $DOCKER_IMAGE'
                }
            }
        }
    }

    post {
        always {
            // Clean up the workspace after the pipeline finishes
            cleanWs()
        }
    }
}